### ISSUE TITLE
add logging

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#17]
add proper logging with python, and refactor existing print statements to use it.

**Comment by kshefchek** [comment]
I've added a logger to the Source class with commit c561640.  I'll start adding this to other classes as well except for ones being actively developed to avoid conflicts.  I can also go ahead and add some more command line args to control this.  Right now I have an option for -q or --quiet to set the level to Warnings and above.  Otherwise the logger is set to debug.

**Comment by nlwashington** [comment]
i think this is finished as of commit 648fe12.
