### ISSUE TITLE
MGI:3514027 is classified as a gene

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#171]
MGI:3514027 is being classified as a gene, even though it ought to be filtered out of the pipeline.  It should be added as owl:sameAs MGI:3056903 which is the variant of the same name.

(Note that in MGI, MGI:3514027 redirects to MGI:3056903)

**Comment by nlwashington** [comment]
well... so i thought i had taken care of this... but it turns out the ontology is smarter than i am.

for all the transgenes in MGI, they typically also have an "allele" that is also the transgene, and they have logic in their website to redirect the trans-gene (marker) to to the allele page.
* MGI's page for this allele: http://www.informatics.jax.org/accession/MGI:3056903
* you'll see it gets redirected to the same here: http://www.informatics.jax.org/accession/MGI:3514027

i was trying to be tricky, and had a special case for these transgenes where i did the following: 
*  "type" them as [SO:transgenes](http://sequenceontology.org/browser/current_svn/term/SO:0000902)
*  make them individuals, rather than classes
*  make a sameAs relationship between the "allele" version and the "marker" version

BUT, it turns out that a transgene is_a gene (of course), so all the transgenes are then being classified as genes, because the ontology tells us so.  

the implications of this are that when we make any gene-X associations for golr and owlsim resulting from cypher queries, we will necessarily get all these transgenes.  i was assuming this was unacceptable, and hence this ticket being labeled as a bug.  but perhaps it's not a bug?  

@mbrush or @cmungall can you comment on whether or not it is okay?

FWIW, here's our pages for these:
http://beta.monarchinitiative.org/gene/MGI:3514027  <-- as the gene
http://beta.monarchinitiative.org/variant/MGI:3056903 <-- as the variant

**Comment by cmungall** [comment]
Interesting. There are definitely cases where we need to avoid mixing up 'native' genes and transgenes. For a basic query like 'list all protein coding genes' we want on the order of 20k results.

Currently SO doesn't provide this ability easily. transgene is kind of a single-child by 'nativeness' criteria; there is no gene defined using SO:0000782 ! natural 
But it's not clear that adding 'native gene' would be of benefit. Most people do not classify at this level, there is a default assumption going on.

How about we explicitly tag non-transgenes with 
SO:0000782 ! natural
?

The default behavior for gene would be inclusive, but it would provide us hooks for drilling down

**Comment by nlwashington** [comment]
so, would this tagging be at the level of dipper, or at the level of the categories in scigraph?

**Comment by mbrush** [comment]
I would agree that this is a bug. I think it best to show the mgi transgene-X associations as variant-X associations rather than gene-X associations to users.  
 
I like Chris' suggestion to tag non-transgenes with the attribute SO:0000782 ! natural (and/or we could also tag the transgenes with  the attribute SO_0000781 ! transgenic). Then use this tag to filter what we display in Monarch.  This is preferable to creating a 'natural gene' class  in SO. 
 
Just to toss another option on the table, it might be simpler and more consistent not to type the 'gene' version of the transgene (i.e. MGI:3514027) as an SO:0000902 ! transgene, but instead type it as an SO_0001218 ! transgenic_insertion. This class is a descendent class of sequence_alteration  -> insertion, so we  avoid in inference that MGI:3514027 is a gene. And we still capture the transgenic nature of the feature. 
 
Possible 'pros' of this approach:
 * We avoid a situation where we treat natural genes as classes and transgenes as individuals, by only classifying individuals such as MGI:3514027 as transgenic_insertions and not as transgenes.  
 * Ontologically, a transgene isn't a transgene until it becomes an insertion anyway, right? So the idea of a 'transgene' independent of being inserted into another genome doesn't make sense anyway.
 * Keep in mind that SO genes are defined as necessarily producing a functional transcript, and I would guess it is not always the case that MGI transgenes will produce a functional transcript.  So it may not be entirely correct to classify all MGI 'transgenes' as SO transgenes  (but I don't think we are too concerned with this finer point)

Possible cons: 
 * We wont have SO 'transgene' classes or instances in our mgi data.  Any queries for transgenes would have to be framed as queries for transgenic insertions.
 * Also, if there are cases where we want the notion of a 'gene; to include/return transgenes, this approach is not ideal as we frame transgenes only as instances of transgenic_insertions.
 
Ultimately, I am on board with the first solution if it is most practical - just presenting a second option for consideration.

**Comment by cmungall** [comment]
I agree, nice analysis.

Of course, there have been multiple cases of historic natural transgenic insertions becoming fixed, where we think of this as just a 'gene'. And this may well happen with 'artificial' transgenic insertions too (hopefully for the better of the environment and human health).

Another reason in favor of using the insertion: I find it cleaner to think of Mus musculus as being largely wild type, and keeping the set of genes for that species as those found in wild type. Everything else is a variation relative to this reference.

**Comment by cmungall** [comment]
> so, would this tagging be at the level of dipper, or at the level of the categories in scigraph?

I can see it being useful having categories

Slight problem with the transgene approach, they would end up in a different branch, so they wouldn't end up with the same category. I think it could be useful to broadly group (wild type) genes on the one hand as a disjoint category from varianty-like things on the other.

![al](https://cloud.githubusercontent.com/assets/50745/10682803/44d21070-78ef-11e5-8bba-7c17314532a4.png)

**Comment by mbrush** [comment]
Re-reading the past posts for  this ticket and think that a good solution here might be to create defined species-specific 'gene' class (e.g. mus musculus gene = gene and in_taxon some mus musculus).  I have started doing this in GENO already to allow grouping of genes by taxon, and this can serve as a way to group natural genes separately from transgenes (taxon-specific hierarchies holding only 'natural genes').  For transgenes, I would say that even it the Tg encodes a full mouse gene, it would not qualify as a 'mus musculus gene' because its provenance includes non-natural/non-evolutionary processes of human intervention.

So our gene hierarchy would look like this:

	gene
		mus musculus gene
		danio rerio gene
		homo sapiens gene
		transgene
		
MGI:3514027 (the 'gene' id) would be asserted as a transgene, and MGI:3056903 (the variant/insertion) would be classified as a transgenic insertion.  

Monarch could be configured to only display genes under the taxon-specific hierarchies - getting us the distinction we need between natural and transgenic genes without explicitly modeling natural vs unnatural gene classes (because the taxon-specific gene classes imply being natural). And I think this approach is in line with the idea Chris mentioned in his last comment that " it could be useful to broadly group (wild type) genes on the one hand as a disjoint category from varianty-like things on the other." (wild-typey genes go in their taxon-specific hierarchy, and varianty transgenes go in the transgene hierarchy).

The question is, do we create MGI:3514027 as a subclass of transgene, with the MGI:3056903 individual as an 'allele_of' this transgene class?  Or do we create MGI:3514027 as an individual as well (of type 'transgene'), with a sameAs link to MGI:3056903 individual?  Both would seem to have benefits and issues.

**Comment by nlwashington** [comment]
my concern about this is that then we could end up recreating the NCBITaxonomy within GENO or SO, just to get species-specific genes.  that worries me.

**Comment by mbrush** [comment]
I considered this but i think we would only need to represent at the leaf node levels as needed - not the full hierarchy in the NCBI taxonomy.  And there could be benefits to organizing our gene classes to some extend in terms of usability of the gene owl file.

Also, see my addendum to the comment above - if there is no real use case for classifying Tgs as markers and variants, lets not bother (given that it is causing issues for us).

**Comment by nlwashington** [comment]
Ok!  so I will classify any of the MGI Transgene "markers" as transgenic insertions, and make them sameAs the "alleles".  Easy peasy.

**Comment by nlwashington** [comment]
I've added this fix and running on bamboo now.  Should be ready with next graph load.
