### ISSUE TITLE
Developmental Biology

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dipper#175]
Looking at the Pathways tab of 
http://beta.monarchinitiative.org/disease/DOID%3A10595
the first entry is "Developmental Biology" and the PMID is http://www.ncbi.nlm.nih.gov/pubmed/14657022
I guess this is a result of inheritance across some ontology, but "Developmental Biology" seems so general that it is meaningless, and the PMID does not seem to support this claim.
Suggestion: Limit the amount of inheritance involved in pathway inferences and stick only to specific pathways (leaves)

**Comment by nlwashington** [comment]
This data comes from CTD, which may actually get this from Reactome.  They curate 475 genes to this "pathway".  We list it here because one of those genes is annotated one of the Charcot-Marie-Tooth diseases, so through transitivity it is suggested that pathway is involved.  I don't do any other reasoning/inference.

I agree that there are some curated items that are less than stellar (I already filtered out other associations to general terms like "genetic disease".)  

First, I can add this non-pathway (REACT:111045) to the filter list that i remove from CTD.
Second, we can look toward some filtering at graph query time to get only the leaves of the pathways (though I don't know that pathways are that well organized yet in our ontology import.)

**Comment by nlwashington** [comment]
i've scrubbed a few uninformative pathways as suggested.  that's the best I can do on the dipper end for now.  let's see how it pans out for the next release.
