### ISSUE TITLE
need to do something about zebrafish tp53

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/dipper#233]
see this page for example
http://stage.monarchinitiative.org/gene/NCBIGene:1374

I am pretty sure that the top matching zebrafish to carnitine palmitoyltransferase 1A 
should not be tp53. 

This likely comes from separating out the tp53 morpholinos from their parent genotypes. tp53 MOs are used to reduce apoptosis in combination with other MOs. We should not be comparing directly against tp53 alone in this case. 

@mbrush @nlwashington can you take a look at this?
@cmungall could also be something with how the genotypes are populated in OWLsim?

**Comment by cmungall** [comment]
I'll look later, but owlsim should be in sync with data after the next 
dump

**Comment by mbrush** [comment]
This is a timely ticket as I've been meaning to look into how phenotype propagation is being implemented in our current system - i.e. if we actually use the property chains in GENO to reason over the data and materialize these inferred triples, or if there is some rules/logic implemented outside of the ontology (e.g. in SciGraph) that defines how this propagation occurs.  Hoping @cmungall  can shed some light here . . . but regardless, a solution to the issue raised here will be similar.
 
So the issue if I understand correctly is that the tp53 gene will be associated with a large number of phenotypes inappropriately (and this appear as an inappropriately high match for many phenotype-based comparisons in phenogrid) - because of the common use of tp53 morpholinos to limit the apoptotic response in the presence of other MOs that are target primary gene of interest.  It is to this primary gene that the phenotypes of these FISH should propagate, but not to the tp53 gene. This is an analogous problem to the known issue that, with our present property chains, phenotypes may get inappropriately propagated to things like fluorescent protein genes that are used as markers in many transgenic organisms that bear other, primary alterations of interest.
 
The simplest solution here is to use a different parthood property in our genotype partonomy to link to any such variation/gene to which we don’t want infer a phenotypes association  (i.e. one over which phenotypes are not propagated). The challenge here is identifying when it is the case that we should use this other property.  This is straightforward in the marker protein case because we can enumerate these cases where the gene is a marker, and it is always the case that we don’t want to propagate phenotypes here.  This is harder for tp53,  because there are cases when it is appropriate to propagate phenotypes to tp53 - i.e when the aim of the study is indeed to study the effect of tp53 expression, and not simply repress its expression to facilitate interrogation of phenotypes resulting from knock-down of other genes.  We would have to look into the data to define rules that best deliver the desired propagation behavior, but it may be hard to make these completely perfect (e.g. a rule like 'if a MO targeting tp53 is used in combination with another MO, don’t propagate phenotype to tp53' would help, but prohibit some cases where propagation to tp53 is desired).

**Comment by kshefchek** [comment]
This is fixed for mouse and zebrafish, #256 replaces as a more general ticket for all organisms.

**Comment by kshefchek** [comment]
Reference PR: https://github.com/monarch-initiative/dipper/pull/340

This has been fixed by temporarily breaking out mouse and zebrafish gene to phenotype associations into seperate "slim" files.  These are generated by querying intermine for MGI data, and using the clean gene to phenotype file from ZFIN.  The main models are then filtered out of the G2P queries indexed into golr.

This was proposed originally here:
https://github.com/monarch-initiative/dipper/issues/324#issuecomment-225318497
