### ISSUE TITLE
depencence reduction

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#238]
Eliminating, minimizing and deferring dependencies until they are needed
will reduce barriers to adoption for dipper.
For instance using dipper to process ClinVar XML does not involve postgres
so adopting dipper on a freshly installed machine should not by default
expect you to install packages which will not be used.  

Addressing this purely through documentation is one approach 
having a core (skinny) dipper by default which is explicitly extended 
for particular cases is another.

**Comment by kshefchek** [comment]
I've proposed a solution here using importlib: https://github.com/monarch-initiative/dipper/commit/45fdfb79e445fcaf4d02bd57f055dc832f1d9186, however the parent Source class imports psycopg2 (postgres lib), so this defeats the original purpose.  One idea would be to create a PostgresSource subclass (I do something similar [here](https://github.com/monarch-initiative/mckb/blob/master/mckb/sources/MySQLSource.py) with MySQL) and extend any sources that use postgres from this class rather than Source.

**Comment by nlwashington** [comment]
@jnguyenx tracked down the requirements for a fresh installation on a unix (ubuntu) system.  ```psycopg2``` does not require postgres to be installed, but one of the files that it installs - it is available in a related library without having to install all of postgres).  here's the list of libraries that were required for the install:
<pre>
python3-setuptools
python3-dev
libpq-dev
libjpeg-dev
libxml2-dev
libxslt1-dev
</pre>
we can simply add these to the documentation regarding installation.  i suspect few to none of these were required by me on my OSX box because they may have come with XCode.
is this sufficient for you @TomConlin to get started?  or should we reduce the requirements even more?

**Comment by kshefchek** [comment]
I assume libpq-dev is the [issue](https://www.google.com/search?q=install+libpq-dev).  It may be called postgresql-libs on CentOS according to one of those threads.
