### ISSUE TITLE
refactor staining_intensity --> sequence_attribute

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#241]
Stop using has staining intensity (GENO_0000626  ! has_staining_intensity) and just use has sequence attribute (GENO_0000207 ! has_sequence_attribute) - should only affect the ucsc bands files.

**Comment by nlwashington** [comment]
Not that I want to continue the conversation, but this seems strange to me.  The staining intensity is a quality of the actual genomic material derived from the organism, as opposed to being a quality of the information artifact.  Curious why you decided to change your mind on this?

**Comment by mbrush** [comment]
This gets into ontologically dubious territory - what things are qualities of the abstract sequence artifact vs its materialization in DNA.  The SO has historically not really worried about this distinction - e..g 'enzymatic' is an SO sequence attribute that clearly is not a characteristic of the abstract feature, but of the materialization.  For simplicity and consistency, I am just following the same approach.  

has_staining_intensity was previously a subproperty of has_sequence_attribute, so my rationale in eliminating was to just use the parent has_seq_attribute because the range of this property will always be a staining intensity class. So we really gain nothing by creating a separate property to link to staining intensities, and I removed to avoid unnecessary proliferation of relationships.
