### ISSUE TITLE
GENO_0000208 ! has disposition

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/dipper#377]
@mbrush 
Our hpoa and  omia ingests use GENO_0000208 ! has disposition
but that term no longer appears in geno.owl

Will the term reappear or can you give me a replacement term?

**Comment by mbrush** [comment]
This was a temporary relation in early versions of geno, which has since been replaced with http://purl.obolibrary.org/obo/RO_0000091. It can be replaced with this for now, and this issue closed.

However, the usage of this property in HPOA and OMIA is to link traits/phenotypes to their mode  of inheritance.  As per https://github.com/monarch-initiative/GENO-ontology/issues/22, the modeling for mode of inheritance patterns is under review and will be likely be updated in the near future.  

I have created a new ticket (#383) as  reminder to refactor the HPOA and OMIA sources once the inheritance modeling pattern is finalized.
