### ISSUE TITLE
Mutual reuse with ETL code from MyFoo.info and Wikidata

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/dipper#382]
There are multiple ETL pipelines out there. Even if the modeling is specific to dipper, there should be no need to duplicate syntactic parts of ETL

(we are hopefully getting closer to a point where there are rational end-points for many bio databases and the parsing part of ETL becomes unecessary, and everything is purely transform / vocab mapping etc, but we are not there yet)

This diagram shows how this might work in the context of MyVariant.info etc. This ETL framework creates nested python objects / JSON, for loading into ES. If we could take the JSON (either a dump, or via code integration, or via API calls) and start with that, transformation to our OWL models is all we have to do. We would make PRs on the source ETL framework where need be.

Mutually, My\* could take any ttl we produce and use this is a starting point for their ES load. We need not eliminate all overlap, but even getting mindshare on the idiosyncracies of some sources is a win.

<img width="894" alt="translator-etl" src="https://cloud.githubusercontent.com/assets/50745/19136714/774b70cc-8b23-11e6-9d6c-64fdc1c88370.png">

source graffle in translator dropbox

**Comment by newgene** [comment]
@cmungall totally agree. BioThings APIs (how we call [MyGene.info ](http://mygene.info) and [MyVariant.info](http://myvariant.info), and future APIs for drugs/diesease..., collectively, which was referenced as "My*" in your original post) were built with the extension of data sources from the third-party in mind. All data source modules are independent each other (with very few exceptions). Only the data-source specific file-parsing, data structure description are needed for each data source. The rest, like merging, indexing, querying via API and periodic updating, are all abstracted out of the third-party developers. Existing data source module examples from [MyGene.info ](http://mygene.info) and [MyVariant.info](http://myvariant.info) projects are here:

https://github.com/SuLab/mygene.info/tree/master/src/dataload/sources

https://github.com/SuLab/myvariant.info/tree/master/src/dataload/contrib

We are working on further abstraction, so that the data source module does not even have to be included in our repo, and it can be a standalone python module maintained by third-party (roughly analog to django apps).

Our team would be excited to work with the dipper team to synchronize our efforts on data ETL.

**Comment by balhoff** [comment]
I'm curious if either of you have ever looked at linked data integration tools like these:

* [Silk](http://silkframework.org)
* [LDIF](http://ldif.wbsg.de)

I just came across them on the Jena mailing list and wasn't aware of them before. Definitely not as lightweight as dipper, but the Silk graphical editor looks kind of interesting.

**Comment by cmungall** [comment]
I looked at Silk a long time ago, seems to have come along. Not heard of LDIF. We did take a deep dive into WebKarma, which seems similar.

We opted for something programmatic in the end. Often you just need to write python code. Also there are many libraries in python for handling common formats. Having said that, we could do with dipper being more declarative.

**Comment by kshefchek** [comment]
@cmungall okay to close?  I propose we break out into actionable tickets.
