### ISSUE TITLE
Some test files disappeared

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/dipper#387]
I tried to run the dipper integration test project, but the panther test file disappeared.

**Comment by jnguyenx** [comment]
Actually there are a couple more:
http://data.monarchinitiative.org/ttl/panther_test.ttl
http://data.monarchinitiative.org/ttl/clinvar_test.ttl
http://data.monarchinitiative.org/ttl/kegg_test.ttl

**Comment by TomConlin** [comment]
They are deleted because they are not being generated by the Jenkins process and the stale test files are not cleared out,  so any tests you have been doing on them are not meaningful.   I can not tell why they are not being generated nor for how long, Jenkins scripts do not seem to have any version control I am aware of.

**Comment by TomConlin** [comment]
Orphanet reports:   
    WARNING:dipper.sources.Orphanet:not configured with disease test ids.
do we have any evidence it has ever produced a test file.
Likewise, I see no indication flybase has had a test daraset.

Panther, kegg, animalqtl and wormbase are now producing test files
there is also a  clinvar test as well but I am still going to redo it
