### ISSUE TITLE
:hasSubject vs RDF[subject]

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#40]
in our associations, we currently use

:hasSubject (and :hasObject) as some kind of monarch-y specific predicates.

@cmungall why not use rdf:subject (object, predicate) ?

**Comment by cmungall** [comment]
There are potential problems in using these predicates in OWL (the RDF properties are uncommitted as to whether they are annotation props or object props or data props - these distinctions are only meaningful in the OWL 'layer' of RDF, and OWL strictly makes these disjoint categories, and you get into trouble if you implicitly commit to disjoint categories)

For this reason, the OWL2 group introduced a new vocabulary:

 * owl:annotatedSource
 * owl:annotatedProperty
 * owl:annotatedTarget

We use this in LEGO (cc @hdietze) mainly because conformance with OWL tools are important here (basically the reified statements look rather nice in Protege)

However, this vocabulary comes with restrictions. The subject of the reification triples are always of type owl:Axiom. And the axiom can't have its own IRI. This is not great for us, as we want to identify our annotations, and we want these to be 'first class' (not an ad-hoc ID property). You can easily do this with another property linking the Axiom to the annotation... but it's not really lightweight.

So, working with @jamesmalone we devised OBAN, https://github.com/jamesmalone/OBAN the idea was to swap this in in place of our ad-hoc vocab. We looked hard at reusing an existing vocab like W3C OpenAnnotation, but none fit the bill. I have one issue open about the final form of the URIs, once decided we can make the switch.

aside to @hdietze we should decide on the long-term form of the LEGO annotations

**Comment by mbrush** [comment]
This all sounds good.  One question - we had earlier discussions about whether these reification properties would be **owl:objectProperties** or **owl:annotationProperties**.  They are defined in OBAN presently as object properties - can I assume this is how we want to use them in Monarch?  Or is there still some debate here (e.g. concerning implications of reification properties being seen by the reasoner)?

**Comment by cmungall** [comment]
I don't think there is any harm in reification properties being seen by the reasoner (adds some overhead, but easy to split out if this is the case).

There are implications in that punning is induced. Not a problem in itself, but could lead to a potentially confusion in the semantics of the same graph being different when inspected by different parts of the toolchain. E.g. in OWL the instance and class would share the same IRI but would be formally different objects.

**Comment by mbrush** [comment]
Interesting points to consider, esp. as there are many other places in the data we might pun class IRIs (e.g. linking a variant to a gene class IRI, or genotype to a taxon IRI , or an association to an evidence code IRI). 

A related question here concerns how to treat properties linking an **association** to things like a **source** and  **evidence**. At present we use *dc:source* as to link to the IRI of a source publication individual (e.g. J:32425). Should *dc:source* be treated as an object property or an annotation property here?  

And for evidence, we use *dc:evidence* to link to an ECO term IRI. Do we want this link to be an object or annotation property, and ultimately do we want to use *oban:has_evidence* here instead of *dc:evidence*?

**Comment by cmungall** [comment]
We should probably be more specific, but good point about dc. We could easily fenkle ourselves when using RDF vocabs that don't commit to OWL interpretations. I'm used to doing this in an ontology when the commitment for dc etc is almost always to an annotation property (since you are attaching directly to a Class). But things get hairier here.

**Comment by mbrush** [comment]
@cmungall  By 'be more specific', you mean explicitly casting the dc properties into owl (as OPs vs APs),right?  

I suspect we would cast dc properties as object properties in cases like we have here (source, evidence), where the subject is an information artifact in our domain (e.g. an annotation) and not a class in our ontology?  I have seen translations of dc into owl that do exactly this, such as [this nice treatment] (http://bloody-byte.net/rdf/dc_owl2dl/) . . . specifically [this translation] (http://purl.org/NET/dc_owl2dl/terms_od) which casts many dc properties as OPs, including 'dc:source'.

So as we finalize with our initial RDF-izing of MGI G2P data, can we go ahead and treat the properties hanging from our association individuals as OPs and see how this works (specifically, the reification properties, as well as dc:source and dc:evidence)?

**Comment by cmungall** [comment]
Sorry, I meant specific properties like 'has evidence' rather than the broader (IMHO) set of dc properties

**Comment by cmungall** [comment]
I'll take a closer look at the bloody bytes thing later. It seems there is still potential for fenkling?

**Comment by nlwashington** [comment]
@cmungall can we go ahead and use the OBAN classes and properties now?  that would mean the following changes:
DC[evidence] ==> RO_0002558 (has_evidence)
MONARCH:hasObject ==> OBAN:association_has_object
MONARCH:hasSubject --> OBAN:association_has_subject
MONARCH:Annotation ==> OBAN:association

any given association also has an evidence code, a publication or some kind of external thing that it references, and then where the association came from (like the organization that the curators work for...MGI, OMIM, etc.)

we have been currently capturing: 
* via DC[source], some kind of PMID
* via DC[evidence], some ECO code

what do we want to do going forward?  perhaps:
* PMIDs via :has_provenance ?  (instead of DC[source])
* the database/organization via DC[source] ?  (we do not currently capture)
* via RO:0002558 (instead of DC[evidence]) to the ECO code

**Comment by cmungall** [comment]
+1 to using OBAN and RO

**Comment by nlwashington** [comment]
what relationship do i use to point to the edge property between the subject and object?  i can't quite tell.  there are two properties, though by their id i don't know if they are right:
association_has_subject_property
association_has_object_property

you might assume association_has_object_property, but this may not be its intended use (given that there is the association_has_subject_property).  can @cmungall or @jamesmalone clarify?

**Comment by nlwashington** [comment]
i will assume association_has_object_property is the correct one for now.  we can change this as it gets updated.

**Comment by nlwashington** [comment]
in summary:

Annotation: —> OBAN:association
:hasSubject —> OBAN:association_has_subject
:hasObject —> OBAN:association_has_object
:hasPredicate —> OBAN:association_has_object_property
dc:evidence —> RO:0002558

**Comment by nlwashington** [comment]
implemented in commit 1455a97.

**Comment by cmungall** [comment]
Just commenting here for anyone happening across this retrospectively. Comments copied from slack:


re: reification. we probably should not have picked our own vocab. We should have chosen rdf or owl. It's unfortunate that owl didn't reuse rdf reification. we essentially have to use owl reification when working in an owl stack, and rdf reification in an rdf stack
7:08
note the canonical way to serialize a PG in RDF in biolink is rdf reification. https://biolink.github.io/biolink-model/about/mapping-rdf.html

Biolink ModelBiolink Model
Mapping Biolink Model to a RDF and RDF*
A high level datamodel for representing biological entities and their associations.
7:09
Note that RDF* is essentially syntactic sugar for RDF reification





7:09
https://blog.liu.se/olafhartig/2019/01/10/position-statement-rdf-star-and-sparql-star/





7:10
I'd like us to move towards RDF* and OWL* for our RDF see https://github.com/cmungall/owlstar

GitHubGitHub
cmungall/owlstar
Ontological Interpretations for Web Property Graphs - cmungall/owlstar





7:10
however, this is complex. SG is built on the OWLAPI stack





7:11
For now, oban reification is not massively problematic, as we know how to generically transform it: to OWL reif, to RDF reif/RDF*, or directly to a PG eg with KGX

**Comment by cmungall** [comment]
This ticket is also relevant: https://github.com/SciGraph/SciGraph/issues/176

**Comment by TomConlin** [comment]
oi. too much bath water not enough baby.
