### ISSUE TITLE
Add try except to handle variable .owl formats

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#401]
OWL file formats appear to be variable (is this correct @cmungall), see http://purl.obolibrary.org/obo/pco.owl as an example.  Instead of expecting XML we should add try/except clauses to test various acceptable formats.

Note this was caught by a travis build: https://travis-ci.org/monarch-initiative/dipper/builds/187602697#L666

**Comment by cmungall** [comment]
What is this test doing?

I thought all ontologies were only every parsed by the OWLAPI

With my OBO hat all ontology release purls should resolve to an RDF dialect to enable parsing from non-OWLAPI frameworks.

But from a Monarch side we should code defensively

**Comment by kshefchek** [comment]
This particular test runs the parser over a subset of IDs.  Since there is no python OWL API (that I know of) we parse ontology files as RDF using RDFLib where we need to explicitly declare the incoming format IIRC.

**Comment by cmungall** [comment]
My error - pco is turtle. RDFLib should handle it

**Comment by TomConlin** [comment]
https://github.com/monarch-initiative/dipper/blob/master/dipper/utils/GraphUtils.py#L574

**Comment by cmungall** [comment]
what is the purpose of the retry? https://github.com/monarch-initiative/dipper/blob/master/dipper/utils/GraphUtils.py#L579

do we expect this to be nondeterministic (is the file local or on a network?)

I suggest if xml fails, try ttl

**Comment by kshefchek** [comment]
@cmungall that is my approach, I have it fixed on a branch.

**Comment by TomConlin** [comment]
> @cmungall    I suggest if xml fails, try ttlwhat is the purpose of the xml-specific retry?

The original author's (OA) expectation must have been  `.owl == .xml` 
I replicated because as the comment directly above the edit notes because I would loose hours when after successfully parsing the actual data dipper would fail with a http timeout fetching an ontology file. Rerunning often worked presumably because the ontology file had been roused from its crypt and shambled off into a cache where it became available in time if requested soon enough.  Without knowing why OA felt it was necessary to rely on the extension to explicitly set the parser it felt foolhardy to strip it out. 

> @cmungall    I suggest if xml fails, try ttl

Easy enough,  however we will be right back where we were w.r.t. timeouts.
at this point I think it is worth attempting to try letting rdflib figure out the format on it own understanding we will have to keep an eye on it.


> @cmungall  why do we parse these ontologies anyway?

!!!!  Because you have told us we have to keep doing it even though we really really do not want to in the slightest. (In fact my clinvar ingest does not, which is why Kent  made a script to add them in post hoc). I have an evil plan to strip all of the ontological statements out of the ingests leaving only the ontological annotations as "hooks" to be wired up with their ontologies within scigraph.

**Comment by cmungall** [comment]
Technically OWL is a language and not a format, so it's not wrong to distribute any valid W3C OWL serialization and call it OWL. However, W3C recommends certain prefixes. (btw the use of 'xml' in rdflib is unfortunate, there are other valid xml representations of OWL that are not the OWL subset of RDF/XML, such as OWL/XML, which is not RDF).

I tell people all kinds of contradictory things then change my mind. Can you remind me of the context, what was my reason for requiring the full parse of the file?

**Comment by TomConlin** [comment]
Do not trust me now. I am under Dan's post biopod influence. My recollection of your reasoning is the .ttl files would not be valid standalone OWL files. Which for my goals of elucidating the validity of the the ingest is not relevant and infact gets in the way when asking "Where exactly did this bit of nonsense come from?"  It also should be 100% redundant with loading ontologies in scigraph.

**Comment by kshefchek** [comment]
@cmungall @TomConlin original discussion here: https://github.com/monarch-initiative/dipper/issues/316

agree it would great to remove if we don't need it.

> btw the use of 'xml' in rdflib is unfortunate, there are other valid xml representations of OWL that are not the OWL subset of RDF/XML, such as OWL/XML, which is not RDF).

rdflib can only deal with RDF, theres no support for OWL.

**Comment by TomConlin** [comment]
I can accept the pco owl file formatted as turtle but it really should parse as valid rdf with common libraries i.e redland rapper  

     rapper -v
     1.4.21
     rapper  -i turtle -c ../raw/ontology/pco.owl
     rapper: Parsing URI file:///home/tomc/Projects/OHSU/dipper/dipper/../raw/ontology/pco.owl with parser turtle
     rapper: Error - URI jE:58 - syntax error
     rapper: Parsing returned 28 triples
 
I thought it might be  obo:IAO_0000111 using itself as both it's subject and its predicate but that is allowed.  I do not see why it fails to parse.

**Comment by kshefchek** [comment]
@TomConlin can this can be moved to https://github.com/PopulationAndCommunityOntology/pco if it is still an issue?
