### ISSUE TITLE
map ucsc cytogenic bands to types

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/dipper#43]
the following banding pattern abbreviations are used in the UCSC band files.  these should be mapped.

acen  : SO:0001795  #regional centromere
gvar : SO:0000628 #chromosomal structural element
stalk  :  SO:0000105 #chromosome arm for now; term request?
gneg : SO:0000450 #interband

all of the following would be specific subclasses (that don't yet exist) of SO:0000341 (chr band)
gpos100
gpos25
gpos50
gpos75

note from http://redmine.soe.ucsc.edu/forum/index.php?t=msg&th=6330&start=0&S=b9baef7808cb7c0e11972e625f95d5cf
"acen" is centromeric;
"stalk" refers to the short arm of acrocentric chromosomes chr13,14,15,21,22;
"gvar" bands tend to be heterochomatin, either pericentric or telomeric.

**Comment by nlwashington** [comment]
by definition, the "interband" feature doesn't seem appropriate for the gneg... it is defined as related to polytene chromosomes, and is a sister term to chr_band.  i think for now it might be best to still label the gneg as a chr_band, and make a term request for gneg to be a subclass of chr_band.

**Comment by nlwashington** [comment]
also, chr_bands are currently not part of chr_arms in SO.  @mbrush does this seem right?

**Comment by mbrush** [comment]
So to summarize where things stand for ticket #42 and #43:

- FALDO fits the bill for modeling location.  Only comment here is that in your example rdf above your use of faldo:begin and faldo:end is not quite right, in that it skips over the blank 'position' node, from which the integer values hang. 

- As for ontology needs, we essentially need classes for gneg and various flavors of gpos regions to be added to SO (or GENO in the interim)?  And also to make sure all subsequence/part_of relations are in place between chromosomal element classes (e.g. chr_bands part_of chr_arms).  The interband issue/misunderstanding seems resolved (will just be mapped to the gneg class).

- @nlwashington I am not clear on what you mean by "it is presently a bit clunky to map the containing regions of a chromosome band, since i have to map it to the generic parent of both chr_band and chr_arm."

- Finally, big picture, are we proposing an owl model of chromosomes, to be added to the Monarch import chain. It would describe: (1)  the nesting/partonomy of chromosome elements (chromosomes > arms > regions> bands > sub-bands); and (2) define the numerical genomic positions of these elements  (using FALDO).  This seems pretty straightforward with the modeling you have proposed in this ticket.

**Comment by nlwashington** [comment]
@mbrush will add required classes to GENO for now.

**Comment by mbrush** [comment]
Added modeling to GENO. Chromosome parts are modeled as sequence features.  Staining intensities (e.g. gpos, gpos25, gneg) are modeled as sequence attributes. Note that most of the term IRIs will be replaced by SO IRIs once term requests are accepted and implemented in SO.  Note also that staining intensity captured as gpos/gneg is modeled as attributes of a chromosome band or sub-band, rather than subtypes of band or sub-band  - e.g. a triple in the data would look like:  

    <:someChromosomeBand      has_staining_intensity        gpos25>

The has_staining_intensity object property may be relabeled/defined to serve a more general need as the modeling develops, but the IRI for this property as defined below should remain correct.

    GENO IRIs:

    The following are sequence features:

    chromosome: SO_0000340
    chromosome part: SO_0000830
        chromosome arm: SO_0000105
            long chromosome arm: GENO_0000629
            short chromosome arm: GENO_0000628
        chromosome region: GENO_0000614   
        chromosome band: SO_0000341
        chromosome sub-band: GENO_0000616
        centromere: SO_0000577
	

    The following are sequence attributes:

    chromosomal band intensity:  GENO_0000618
        gneg: GENO_0000620
        gpos: GENO_0000619
            gpos100: GENO_0000622
            gpos75: GENO_0000623
            gpos50: GENO_0000624
            gpos25: GENO_0000625
        gvar: GENO_0000621
    

    The following are object properties:

    has_staining_intensity: GENO_0000626
    (relation between a chromosome band / sub-band and a chromosomal band intensity)
    is_subsequence_of: RO_0002525
    (relation between a variant or gene and a chromosome part??)

**Comment by nlwashington** [comment]
based on the genomic locations of some of the chr bands, it appears that there are subdivisions of sub-bands:
<pre>
chr1    0   2300000 p36.33  gneg
chr1    2300000 5400000 p36.32  gpos25
chr1    5400000 7200000 p36.31  gneg
chr1    7200000 9200000 p36.23  gpos25
chr1    9200000 12700000    p36.22  gneg
chr1    12700000    16200000    p36.21  gpos50
chr1    16200000    20400000    p36.13  gneg
chr1    20400000    23900000    p36.12  gpos25
chr1    23900000    28000000    p36.11  gneg
chr1    28000000    30200000    p35.3   gpos25
chr1    30200000    32400000    p35.2   gneg

</pre>

in the above case, i do not have a defined band p36.3 in the file.  i only have the definitions of p36.31,32, which are both adjacent to each other, and p36.31 is adjacent to p23.23.  would you like me to type these still as sub-bands (GENO_0000616) ?

**Comment by nlwashington** [comment]
as a followup to the above comment, it still seems relevant that i'd create encompassing bands like:  1p36.3 = [1p36.31,1p36.32]
1p36.2 = [1p36.21,1p36.22, 1p36.23]
1p36.1 = [1p36.11,1p36.12, 1p36.13]

and then i wonder if the rule of thumb for propagating staining intensity would be:
if a band contains a sub-band that is positively stained
  then the containing band would be gpos
  else the containing band would be gneg

**Comment by mbrush** [comment]
@cmungall: We are wrapping up the mapping of ucsc bands to triples and using faldo to model positional information.  One thing that is not clear to me in the faldo model is when the faldo:location property is needed to link the feature instance you are describing to a faldo:Region (which is then linked to begin and end faldo:positions that have a coordinates), and when you can forgo this step and consider the feature you are describing to itself be a faldo:Region (and then you can link it directly to begin and end faldo:positions with coordinates). 

The FALDO manuscript gives the following guidance here: 

     "A key part of the FALDO model is the separation of feature and where a feature
     is found in a sequence record. For this we use the faldo: location object property. 
     This property is used to distinguish between a conceptual gene as an “unit of inheritance” 
     and the corresponding representation of the DNA sequence region encoding the gene as 
     stored in a database."

The features we are describing in the ucsc data are bands defined by the hg19 reference human genome build.  We declare them as instances of classes representing all human instances of a given band. For example, 'chr10q11.22 (hg19)' is an instance of the 'chr10q11.22 (human)' class.  The question is, could 'chr10q11.22 (hg19)', being an instance of a band from a specific reference genome build, also be considered an instance of a faldo:Region (and thus linked directly to a faldo:Position)?  

Our present translation does not do this, but instead links 'chr10q11.22 (hg19)' to a distinct faldo:Region node via the faldo:location property (and then links the faldo:Region to faldo:Positions). This is based on how FALDO handles genes found in records in sequence databases (e.g. the _:geneCheY example [here] (https://github.com/JervenBolleman/FALDO/blob/master/README.md). 

Any feedback appreciated.

**Comment by mbrush** [comment]
Related here, what IRIs to use as faldo:references for contextualizing band position coordinates within a faldo:position.  At present, we use the ucsc hg19 chromosome instance IRIs.

    <http://www.monarchinitiative.org/_:hg19chr8-45600000> a faldo:BothStrandPosition,
                faldo:Position ;
        faldo:position 45600000 ;
        faldo:reference ucsc:hg19chr8 .


This gets tricky when we need a reference for the start and end positions of a complete chromosome . . . do we make a self-referential triple to the same chromosome instance?

**Comment by nlwashington** [comment]
the original purpose of this ticket (to map the SO types for the genomic features) is complete and implemented.  new GENO classes are used where necessary.
