### ISSUE TITLE
Request: Need a dump of all dipper IRIs in a text file

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/dipper#811]
I would like to do some experiments to reduce the extent of Monarch.owl, and need a list of all ontology classes/relation used across all dipper dumps. Basically a txt file that contains every single IRI that has been used anywhere across any dump (including classes, relationships and individuals, if any). Is this something someone can supply me with? Thanks for the help!

**Comment by kshefchek** [comment]
All of the ntriple files for our beta release are here:
https://archive.monarchinitiative.org/201908/ntriples/

This format contains iris and literals delimited by whitespace so something like:
> cat * | sed 's/ /\n/g' | sort -u

I'm running this now and will end up at https://archive.monarchinitiative.org/201908/ntriples/iris.txt

There are nodes that we may want to use in the ontology graph that are not being included in dipper - thinking specifically about go-plus.  In general, the size of the ontology is dwarfed by our data and has not been an issue for us.  I think a slim upheno owl file for owlsim would be more useful.

**Comment by matentzn** [comment]
this is amazing! thanks! Can this be piped through `uniq` as well and be kept up to date?

Even if we chose not to alter the size of monarch.owl in the end this will be hugely useful for validation and qc.

Is it possible to get a reliable list of the IRIs that are not in dipper but you "want to see"? Can you give me an example of why they are not in dipper and should be in the graph anyways?

**Comment by kshefchek** [comment]
> Can this be piped through uniq as well and be kept up to date?

Sure I think the -u should uniquify it

> Even if we chose not to alter the size of monarch.owl in the end this will be hugely useful for validation and qc.

Okay makes sense!

> Is it possible to get a reliable list of the IRIs that are not in dipper but you "want to see"? Can you give me an example of why they are not in dipper and should be in the graph anyways?

It has been a while, but I recall pulling out proteins/chemicals being associated to GO processes and pathways for translator

**Comment by cmungall** [comment]
Note that if we do this it means we must build monarch.owl after the dipper ttl generation in the pipeline. And presumably the ttl files will not be released until the pipeline is done, so the monarch build will need to access some kind of staging area. This increases complexity in contrast to a more decoupled approach. @kltm has thought a lot about this in the GO pipeline (but note the dependency is reversed - GAF generation and validation absolutely depends on the full ontology import chain).

Are we sure that dipper does not depend on monarch.owl? If so that will introduce a cyclic dependency, which increases complexity further.

Also I think we really want to introduce building a triplestore at some point in the pipeline. It's better to support use cases like dumping all URIs via SPARQL than awking an nt file. cc @deepakunni3 @balhoff 

Also also: are we sure we want to exclude HPO classes that are more specific than anything that has been annotated? This deserves broader discussion.

Perhaps the actual approach we want is as follows:

 * curate the set of ontologies we want to bring in carefully, in consultation with dipper team. Ruthlessly remove things we know are not being used that we one put in for random reasons (e.g. ERO)
 * load the whole ontology in the majority of cases
 * in select cases, create subsets in a targeted knowledge-driven rather than data-driven fashion
    - for ncbitaxon (massive), use a ready-made slim like taxslim, or curate the set of organisms we care about and extract a module for that
    - chebi - this is fairly large. I still don't think we need to worry about filtering it, but if we do want to then the upheno import should be fine

While there may be good UI reasons for limiting the set of classes we bring in (to avoid showing people things they do not care about), or in the case of really massive ontologies (ncbitaxon) doing this because we have a myserious possibly Elk bug seems like not a great approach, tail wagging the dog. Also my intuition is that this won't help, and if we have an Elk edge case it is some combination of RO and the heavily axiomatized heavily used mid-level portions of of Uberon/phenotype/ontologies/GO.

Sorry to put further obstacles in your way.....

As a debugging approach, the import chain is "shell-structured", so I would start with inner shell (e.g. upheno, work outwards mammal.owl -> vertebrate.owl -> monarch.owl)

**Comment by kshefchek** [comment]
File available here https://archive.monarchinitiative.org/201908/ntriples/iris.txt.gz, @TomConlin let's make this a part of our qc release.

**Comment by matentzn** [comment]
@kshefchek Awesome thaaaanks!

@cmungall No obstacles! :P no worries. Lets do Monarch.owl as you say (decoupled from dipper) for now! I will roll a bit of QC and some stats based on the IRI list later in the year, so I would still want it (I want to use it a bit to get a rough idea of whether the choice of what we make a "dependency" vs a component makes sense). I also want to understand about everything that enters sci graph that is neither dipper dumps nor monarch.owl. Thanks all for input!

**Comment by cmungall** [comment]
Yes, I think it would be really informative to see what the diff between
trimmed and non-trimmed way!
