### ISSUE TITLE
ClinVar medgen not merging with Mondo

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#874]
It seems at some point Mondo removed equivalence axioms to medgen (is this correct @cmungall @nicolevasilevsky?).  This is an issue for our ClinVar ingest which occasionally links to MedGen when an OMIM id is not available.  Should we be linking to UMLS instead using the MedGen CUI?  For example:

https://www.ncbi.nlm.nih.gov/clinvar/RCV000003535.4/

Does not show up on:
https://beta.monarchinitiative.org/variant/ClinVarVariant:3368

**Comment by cmungall** [comment]
we have medgen xrefs in source - need to check if they are somehow filtered
on release

**Comment by kshefchek** [comment]
@cmungall @nicolevasilevsky curious if there is any follow up on this?

**Comment by nicolevasilevsky** [comment]
I can't help here, my apologies!

**Comment by cmungall** [comment]
These are in the release

```
$ grep -A2 C1266042 mondo.owl
    <!-- http://linkedlifedata.com/resource/umls/id/C1266042 -->

    <owl:Class rdf:about="http://linkedlifedata.com/resource/umls/id/C1266042">
        <owl:equivalentClass rdf:resource="http://purl.obolibrary.org/obo/MONDO_0017885"/>
    </owl:Class>
```

I expect this is a prefix this?

**Comment by kshefchek** [comment]
Ah okay this is probably an identifier issue, we're using the IRI https://www.ncbi.nlm.nih.gov/medgen/C1266042.  So basically all medgen IDs are just UMLS CUIs?  If so we'll just prefix these all as UMLS: and it should work.

**Comment by cmungall** [comment]
OK, it's confusing. You'll see on
https://www.ncbi.nlm.nih.gov/medgen/C1266042 there is a "UID" of 266091. In
Mondo we represent this as MEDGEN:266091 (although these are not complete,
we avoid including these as they are redundant with the CUIs).

You'll see they also have a "CUI" of C1266042. Most of the time these are
UMLS CUIs, so we say UMLS:C1266042, which expands to the URI I showed. Now,
sometimes it's medgen's own extension to UMLS, (they have CUIs of CNxxxx).
So maybe we shouldn't really treat these uniformly with the UMLS prefix.
But it simplifies things a lot, rather than proliferating prefixes and
repetitions...

**Comment by kshefchek** [comment]
> So maybe we shouldn't really treat these uniformly with the UMLS prefix.
But it simplifies things a lot, rather than proliferating prefixes and
repetitions...

Sounds like you're still sorting through the right approach?  Let me know what you decide and I'll implement on the dipper side

**Comment by cmungall** [comment]
no, only if you require true medgen IDs. Looks like you are using the UMLS
ones so nothing needs done on the mondo side
