### ISSUE TITLE
Create a generic association class or refactor Assoc

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/dipper#96]
I think it could be useful to have a generic association class.  We have a couple of model classes that are almost identical and could be refactored into this class, specifically Chem2Disease and InteractionAssoc.

We could create a generic association class that is a subclass of Assoc.

Or alternatively, refactor Assoc as a concrete class and add the typical "association" parameters to the constructor defaulting to None, although this sounds a little messy.  We have this commented as an abstract class, but I notice we cheat in a few places and create instances of it.

My preference would be towards the former, but @bryanlaraway @nlwashington curious about your thoughts.

**Comment by nlwashington** [comment]
yes, happy to have a generic association class... your plan seems reasonable.  i probably did cheat, because it was one of the first things i did in dipper, and didn't totally understand python at the time.  at your earliest convenience, please refactor and streamline the code as you see fit.  placing in parking lot as not required for next release.

**Comment by nlwashington** [comment]
This has been implemented, moving all associations into a new "assoc" module.  @kshefchek review at your leisure, and reopen if you find issues.
